In [1]:
import numpy as np 

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[0:5]=100
#broadcasting

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr =np.arange(0,11)

In [12]:
slice_of_arr = arr[1:6]

In [13]:
slice_of_arr[1:3]=100

In [14]:
slice_of_arr

array([  1, 100, 100,   4,   5])

In [15]:
arr

array([  0,   1, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [16]:
arr_copy = arr.copy()
# call copy to copy an array otherwise goes to original array

In [18]:
arr_copy[:]=100

In [19]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
arr

array([  0,   1, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [23]:
# matrix[row,col] or matrix[row][col]
mat = np.random.rand(3,3)

In [24]:
mat

array([[0.6095223 , 0.40198625, 0.36896871],
       [0.54064108, 0.08401233, 0.41123183],
       [0.07051882, 0.58241385, 0.70299317]])

In [26]:
mat[0]

array([0.6095223 , 0.40198625, 0.36896871])

In [27]:
mat[2]

array([0.07051882, 0.58241385, 0.70299317])

In [28]:
mat[1,1]

0.0840123297643518

In [29]:
mat[0,2]

0.36896870759131706

In [30]:
mat

array([[0.6095223 , 0.40198625, 0.36896871],
       [0.54064108, 0.08401233, 0.41123183],
       [0.07051882, 0.58241385, 0.70299317]])

In [35]:
mat[:2,1:]

array([[0.40198625, 0.36896871],
       [0.08401233, 0.41123183]])

In [43]:
mat[1:3,:2]
# simpler equivalent mat[1:,:2]

array([[0.54064108, 0.08401233],
       [0.07051882, 0.58241385]])

In [45]:
# conditional selection
arr = np.arange(1,11)
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
bool_arr = arr>4

In [47]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[arr>4]
#common

array([ 5,  6,  7,  8,  9, 10])