In [1]:
import numpy as np 

In [2]:
# create nympy array
myList =[1,2,3]
x = np.array(myList)
type(x)

numpy.ndarray

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [5]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [6]:
np.arange(0,5,2)

array([0, 2, 4])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# np.linspace(0,10,3)
np.linspace(0,10,51)
# getting evenly spaced numbers

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5,5)
# random from 0-1

array([[0.26425457, 0.51698867, 0.06376307, 0.69885324, 0.64632618],
       [0.34597294, 0.0780671 , 0.77351155, 0.95422378, 0.45283666],
       [0.57193911, 0.59849566, 0.53602588, 0.53625023, 0.64051481],
       [0.52362955, 0.53143189, 0.08773636, 0.21030663, 0.77607041],
       [0.20160526, 0.77019822, 0.45828737, 0.93232703, 0.75629965]])

In [25]:
np.random.randn(5,5)
# standard normal distrubtion random

array([[-0.82589135, -0.44941113,  0.50299356, -0.12469261, -1.78886509],
       [ 0.63522963,  2.0096803 ,  2.09690134,  0.52109398,  0.55812669],
       [ 0.76521999, -0.37726281, -1.08931177,  0.18104941, -0.96267249],
       [-0.50155051, -0.84022344,  1.778884  ,  0.48360264,  0.49688997],
       [ 0.78854432,  1.26169803, -0.18745187, -0.61796376,  0.93286945]])

In [27]:
np.random.randint(1,100,10)

array([49, 94, 92, 33, 46, 17, 13, 69, 47, 97])

In [28]:
arr= np.arange(25)
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([26, 46, 36, 15,  7, 38, 44, 27, 12,  7])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [45]:
arr.dtype

dtype('int64')

In [51]:
ranarr #get random array

array([26, 46, 36, 15,  7, 38, 44, 27, 12,  7])

In [52]:
ranarr.argmax()

1

In [53]:
ranarr.argmin()

4